version: '3.8'

services:
  postgres-user:
    image: postgres:16-alpine3.18
    container_name: postgres-user
    networks:
      - custom_network
    environment:
      POSTGRES_DB: user_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cata1609

  user-management-app:
    build: ./UserMicroService
    image: users:latest
    container_name: user-management-app
    networks:
      - custom_network
    environment:
      DB_IP: postgres-user
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: cata1609
      DB_DBNAME: user_ms
    depends_on:
      - postgres-user
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`) || PathPrefix(`/user`)"
      - "traefik.http.middlewares.user-strip.stripprefix.prefixes=/user"
      - "traefik.http.routers.user.middlewares=user-strip"
      - "traefik.http.services.user.loadbalancer.server.port=8084"

networks:
  custom_network:
    external: true
