version: '3.8'

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24

services:
  traefik:
    image: traefik:v3.2
    container_name: traefik
    ports:
      - "80:80"      # HTTP pentru acces la servicii
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_logs:/var/log/traefik
    networks:
      custom_network:
    command:
      - --api.insecure=true                       # Dashboard fără autentificare
      - --providers.docker                       # Monitorizare containere Docker
      - --accesslog=true                         # Log-uri acces
      - --accesslog.filepath=/var/log/traefik/access.log
      - --log.level=DEBUG                        # Nivel log pentru depanare
      - --entrypoints.web.address=:80            # Ascultă pe portul 80

  postgres-user:
    image: postgres:16-alpine3.18
    container_name: postgres-user
    networks:
      custom_network:
        ipv4_address: 172.16.0.8
    environment:
      POSTGRES_DB: user_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cata1609

  user-management-app:
    build: ./UserMicroService
    image: users:latest
    container_name: users
    networks:
      custom_network:
        ipv4_address: 172.16.0.9
    environment:
      DB_IP: 172.16.0.8
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: cata1609
      DB_DBNAME: user_ms
    depends_on:
      - postgres-user
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`) || PathPrefix(`/user`)"
      - "traefik.http.services.user.loadbalancer.server.port=8084"

  postgres-device:
    image: postgres:16-alpine3.18
    container_name: postgres-device
    networks:
      custom_network:
        ipv4_address: 172.16.0.4
    environment:
      POSTGRES_DB: device_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cata1609

  device-management-app:
    build: ./DeviceMicroService
    image: devices:latest
    container_name: devices
    networks:
      custom_network:
        ipv4_address: 172.16.0.5
    environment:
      DB_IP: 172.16.0.4
      DB_PORT: 5432  
      DB_USER: postgres
      DB_PASSWORD: cata1609
      DB_DBNAME: device_ms
    depends_on:
      - postgres-device
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.device.rule=Host(`device.localhost`) || PathPrefix(`/device`)"
      - "traefik.http.services.device.loadbalancer.server.port=8081"

  postgres-measure:
    image: postgres:16-alpine3.18
    container_name: postgres-measure
    networks:
      custom_network:
        ipv4_address: 172.16.0.6
    environment:
      POSTGRES_DB: measure_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cata1609
    expose:
      - 5432

  measure-management-app:
    build: ./MCMicroService
    image: measure:latest
    container_name: measure
    networks:
      custom_network:
        ipv4_address: 172.16.0.7
    environment:
      DB_IP: 172.16.0.6
      DB_PORT: 5432  
      DB_USER: postgres
      DB_PASSWORD: cata1609
      DB_DBNAME: measure_ms
      DEVICE_CONTAINER_NAME: 172.16.0.5
      DEVICE_CONTAINER_PORT: 8081
    ports:
      - "8082:8082" 
    depends_on:
      - postgres-measure

  frontend:
    build: ./Frontend_EnergyApp
    image: client:latest
    container_name: client
    ports:
     - "4200:4200"  # Mapare port container -> port gazdă
    environment:
        NG_APP_HOST_USER_API: http://user.localhost
        NG_APP_HOST_DEVICE_API: http://device.localhost
        NG_APP_HOST_MEASURE_API: http://measure.localhost
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
        - "traefik.http.services.frontend.loadbalancer.server.port=4200"


