version: '3.8'

services:
  postgres-device:
    image: postgres:16-alpine3.18
    container_name: postgres-device
    networks:
      - custom_network
    environment:
      POSTGRES_DB: device_ms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cata1609

  device-management-app:
    build: ./DeviceMicroService
    image: devices:latest
    container_name: device-management-app
    networks:
      - custom_network
    environment:
      DB_IP: postgres-device
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: cata1609
      DB_DBNAME: device_ms
    depends_on:
      - postgres-device
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.device.rule=Host(`device.localhost`) || PathPrefix(`/device`)"
      - "traefik.http.middlewares.device-strip.stripprefix.prefixes=/device"
      - "traefik.http.routers.device.middlewares=device-strip"
      - "traefik.http.services.device.loadbalancer.server.port=8081"

networks:
  custom_network:
    external: true
